name: libra-daq
channels:
  - conda-forge
  - defaults
dependencies:
  - dash
  - plotly
  - pandas
  - pyarrow  # just to avoid a deprecation warning
  - pip
  - pip:
    - dash_daq
    - dash_bootstrap_components